<a href="https://colab.research.google.com/github/adgcal/Anjan_collab_R/blob/main/quiz1_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



1. What is the function used to create a new  entity in R?
- a) vector()
- b) array()
- c) list()
- d) matrix
- e) dataframe 
- f) factor 
- g) list of list


In [17]:
# a) Create a new vector
my_vector <- c(1, 2, 3, 4, 5)
my_vector


[1] 1 2 3 4 5

In [19]:
# b) Create a new array

my_array <- array(1:12, dim=c(6, 2))
my_array

[,1] [,2]
[1,] 1     7  
[2,] 2     8  
[3,] 3     9  
[4,] 4    10  
[5,] 5    11  
[6,] 6    12

In [21]:
# c) Create a new list

my_list=c('cat','dog',1,2,3)
my_list

[1] "cat" "dog" "1"   "2"   "3"

In [27]:
# d) Create a new matrix
my_matrix=matrix(1:24,nrow=3,ncol=8,byrow=TRUE)
my_matrix


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  1    2    3    4    5    6    7    8  
[2,]  9   10   11   12   13   14   15   16  
[3,] 17   18   19   20   21   22   23   24

In [28]:
# d) Create a new matrix another way

my_matrix=matrix(1:24,nrow=3,ncol=8,byrow=FALSE)
my_matrix


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    4    7    10   13   16   19   22  
[2,] 2    5    8    11   14   17   20   23  
[3,] 3    6    9    12   15   18   21   24

In [37]:
# e) Create a data frame 
df=data.frame(x=c(1,2,3),y=c(4,5,6),ncol=3)
names(df)<- c('a','b','c')
df

a b c
1 1 4 3
2 2 5 3
3 3 6 3

In [41]:
# f) Create a vector of categorical data
my_vector <- c("red", "blue", "green", "green", "red", "blue")

# Convert the vector to a factor
my_factor <- factor(my_vector)
my_factor
levels(my_factor)

[1] red   blue  green green red   blue 
Levels: blue green red

[1] "blue"  "green" "red"

In [55]:
# g) list of list 
# Create a list of lists
# Create a list of lists with information about different animal species
animal_data <- list(
  list(
    species = "Lion",
    habitat = "Savannah",
    diet = c("meat", "occasionally plants"),
    conservation_status = "Vulnerable"
  ),
  list(
    species = "Panda",
    habitat = "Bamboo forest",
    diet = "bamboo",
    conservation_status = "Endangered"
  ),
  list(
    species = "Kangaroo",
    habitat = "Grasslands",
    diet = "plants",
    conservation_status = "Least concern"
  )
)


for (i in 1:length(animal_data)) {
  cat("Species: ", animal_data[[i]]$species, "\n")
  cat("Habitat: ", animal_data[[i]]$habitat, "\n")
  cat("Diet: ", paste(animal_data[[i]]$diet, collapse = ", "), "\n")
  cat("Conservation status: ", animal_data[[i]]$conservation_status, "\n\n")
}

Species:  Lion 
Habitat:  Savannah 
Diet:  meat, occasionally plants 
Conservation status:  Vulnerable 

Species:  Panda 
Habitat:  Bamboo forest 
Diet:  bamboo 
Conservation status:  Endangered 

Species:  Kangaroo 
Habitat:  Grasslands 
Diet:  plants 
Conservation status:  Least concern 



# Write an add on to the list of list to get  the following output
Species:  Lion 
Habitat:  Savannah 
Diet:  meat, occasionally plants 
Conservation status:  Vulnerable 

Species:  Panda 
Habitat:  Bamboo forest 
Diet:  bamboo 
Conservation status:  Endangered 

Species:  Kangaroo 
Habitat:  Grasslands 
Diet:  plants 
Conservation status:  Least concern 
